#!/bin/bash
#
# Perform necessary rumm setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
DEST_DIR=/opt/rumm

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

ln -sf $DEST_DIR/embedded/bin/rumm /usr/bin || error_exit "Cannot link rumm to /usr/bin"

echo "Thank you for installing rumm!"

exit 0
